/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Thu Sep 15 12:35:58 KST 2011 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"Linux"
#define OS_VERSION		"Linux/2.6.15-1.2054_FC5smp"
#ifdef USE_EFM_PATCH
#define OS_URL                  "http://www.iptime.com/"
#else
#define OS_URL			"http://www.kernel.org/"
#endif

/* full path of the file database */
#define DEFAULT_DB_PATH		"/tmp/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/tmp/minidlna"

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
/* #undef USE_DAEMON*/

/* Enable if the system inotify.h exists.  Otherwise our own inotify.h will be used. */
/*#define HAVE_INOTIFY_H*/

/* Enable if the system iconv.h exists.  ID3 tag reading in various character sets will not work properly otherwise. */
#define HAVE_ICONV_H

/* Enable NETGEAR-specific tweaks. */
/*#define NETGEAR*/
/* Enable ReadyNAS-specific tweaks. */
/*#define READYNAS*/
/* Compile in TiVo support. */
/*#define TIVO_SUPPORT*/
/* Enable PnPX support. */
#define PNPX 0

#endif
