<script>
var EXPERTCONF_ADVERTISE_ADDSTR = "添加..";
var EXPERTCONF_ADVERTISE_DELSTR = "删除..";
var EXPERTCONF_ADVERTISE_APPLYSTR = "应用..";

var EXPERTCONF_ADVERTISE_URLREDIR_INVALID = "请检查通知的网址";
var EXPERTCONF_ADVERTISE_CYCLE_INVALID = "请检查一个周期.";
var EXPERTCONF_ADVERTISE_BTNMSG_INVALID = "请检查用户短语按钮";
var EXPERTCONF_ADVERTISE_USERMSG_INVALID = "确认时请检查用户的短语";
var EXPERTCONF_ADVERTISE_USERMSG2_INVALID = "确认后请检查用户的短语";
var EXPERTCONF_ADVERTISE_WHITELIST_INVALID = "请检查白名单.";

var EXPERTCONF_ADVERTISE_NOCHECK_DEL = "请检查复选框";
var EXPERTCONF_ADVERTISE_IPRANGE_INVALID = "IP范围无效";
var MSG_DESC_TOO_LONG = '您可以输入255字节\n如果非ascii字符是3个字节\n当前字节 : ';
var MSG_DESC_TOO_LONG2 = '您可以输入128字节\n如果非ASCII字符是3字节\n当前字节 : ';
var ACCESSLIST_WRITE_EXPLAIN="说明为空."
</script>
