<script>
var EXPERTCONF_PPTPVPN_VPN_ACCOUNT_IS_BLANK="VPN 账号无效";
var EXPERTCONF_PPTPVPN_VPN_PASSWORD_IS_BLANK="VPN 密码为空";
var EXPERTCONF_PPTPVPN_IP_ADDRESS_IS_INVALID="IP 地址为空";
var EXPERTCONF_PPTPVPN_DO_YOU_WANT_DELETE="是否要删除账号?";
var EXPERTCONF_PPTPVPN_IPADDR_OVERLAP="IP 地址重叠";
var EXPERTCONF_PPTPVPN_ACCOUNT_OVERLAP="VPN 账号重叠.";

var EXPERTCONF_PPTPVPN_APPLYSTR = '应用...';
var EXPERTCONF_PPTPVPN_DISCONNSTR = '断开选中的用户..';
var EXPERTCONF_PPTPVPN_DELETESTR = '删除所选用户..';
var EXPERTCONF_PPTPVPN_ADDSTR = '添加新用户..';
var EXPERTCONF_PPTPVPN_NOSELECT = '没有选择项.';
</script>
