<script>
var EXPERTCONF_DDNS_DELCONFIRM = "你想要删除DDNS?";
var EXPERTCONF_DDNS_ADDSTR = "DDNS 增加..";
var EXPERTCONF_DDNS_DELSTR = "DDNS 删除..";
var EXPERTCONF_DDNS_REFRESHSTR = "DDNS 刷新..";
var EXPERTCONF_DDNS_HOSTNAMECHECK = "请输入一个主机名";
var EXPERTCONF_DDNS_USERIDCHECK = "请输入一个用户ID";
var EXPERTCONF_DDNS_CAPTCHACHECK = "请输入安全码";
var DDNS_HOSTNAME_RULE_TXT="无效的DDNS主机名"
var SYSCONF_LOGIN_NEED_CAPTCHA_CODE="填写安全码"
var EXPERTCONF_DDNS_HOSTNAME_IS_BLANK ="主机名称为空"
var EXPERTCONF_IPTIMEDNS_NOMORE_WANRING1 ="没有更多的IPTIME DDNS主机"
var EXPERTCONF_DDNS_HOSTNAME_NOT_IPTIMEORG ="主机名称必须是以iptime.org结尾"
var EXPERTCONF_IPTIMEDDNS_INVALID_USERID="仅仅E-mail地址有用"
var EXPERTCONF_DYNDNS_NOMORE_WANRING1="没有更多的DDNS主机"
var MSG_BLANK_ACCOUNT="输入用户名"
var MSG_BLANK_PASSWORD="输入密码"
</script>
