<script>
var NETCONF_WANSETUP_APPLYSTR = '应用...';
var NETCONF_WANSETUP_CONNSTR = '连接...';
var NETCONF_WANSETUP_DISCONNSTR = '断开...';


var NETCONF_INTERNET_DHCP_MTU_INVALID="MTU不超过1500.";
var NETCONF_INTERNET_PPP_MTU_INVALID="MTU为1492以上.";
var NETCONF_INTERNET_KEEP_ALIVE_MSG="最大空闲时间无效.";
var NETCONF_INTERNET_GW_INVALID_NETWORK="默认网关与内部网络相同.";
var NETCONF_WANSETUP_CONFIRM_WANINFO="是否要确认广域连接信息?";
</script>
