<script language="javascript" type="text/javascript">

var WIRELESSCONF_BASICSETUP_AUTOCHANNEL_STRING = '自动';
var WIRELESSCONF_BASICSETUP_UPPERCHANNEL = '下';
var WIRELESSCONF_BASICSETUP_LOWERCHANNEL = '上';
var WIRELESSCONF_BASICSETUP_TITLESTR = '无线网络的选择';
var WIRELESSCONF_BASICSETUP_DEFNET = '默认的无线网络';
var WIRELESSCONF_BASICSETUP_GSTNET = '访客网络';
var WIRELESSCONF_BASICSETUP_WPSCONNBTN = 'WPS';
var WIRELESSCONF_BASICSETUP_SECOND = '秒';

var WIRELESSCONF_WPSSETUP_PROCESSING = '单击WPS按钮的无线设备';
var WIRELESSCONF_WPSSETUP_CONFIGURED = '连接成功';

var WIRELESSCONF_BASICSETUP_SSID_BLANK = '请输入网络SSID';
var WIRELESSCONF_BASICSETUP_SSID_OVERFLOW = 'SSID 长度太长.\n非ASCII字符有3个字节.\nSSID名称长度: ';
var WIRELESSCONF_BASICSETUP_SSID_UNPERMITTED = '有特殊字符，不允许的SSID';
var WIRELESSCONF_BASICSETUP_RADIUSSERVER_INVALID = '请输入正确的 RADIUS 服务器IP地址';
var WIRELESSCONF_BASICSETUP_RADIUSPORT_INVALID = '请输入正确的 RADIUS 端口';
var WIRELESSCONF_BASICSETUP_RADIUSSECRET_INVALID = '请输入 RADIUS 密码';
var WIRELESSCONF_BASICSETUP_WPAPSK_BLANKED = '请输入一个网络密码';
var WIRELESSCONF_BASICSETUP_WPAPSK_INVALID = '必须输入至少8个字符的密码';
var WIRELESSCONF_BASICSETUP_WPAPSK_HEX_INVALID = '如果输入64个字符密码,\n密码必须是十六进制字符串';
var WIRELESSCONF_BASICSETUP_RXRATE_INVALID = '无效的接收率';
var WIRELESSCONF_BASICSETUP_TXRATE_INVALID = '无效的发射率';
var WIRELESSCONF_BASICSETUP_REGULATION_WARNING = '';
var WIRELESSCONF_BASICSETUP_WEP_NOTSUPPORT = 'WEP 认证太弱了以致不支持';

var WIRELESSCONF_EXTENDSETUP_TXPOWER_BLANKED = '请输入功率';
var WIRELESSCONF_EXTENDSETUP_TXPOWER_INVALID = 'Tx 功率值必须在 1 ~ 100';
var WIRELESSCONF_EXTENDSETUP_BEACON_BLANKED = '请输入Beacon值';
var WIRELESSCONF_EXTENDSETUP_BEACON_INVALID = 'Beacon 值必须在 50 ~ 1024';
var WIRELESSCONF_EXTENDSETUP_RTS_BLANKED = '请输入一个RTS门阀';
var WIRELESSCONF_EXTENDSETUP_RTS_INVALID = 'RTS门阀必须为 0 ~ 2347';
var WIRELESSCONF_EXTENDSETUP_FRAG_BLANKED = '请输入Fragmentation';
var WIRELESSCONF_EXTENDSETUP_FRAG_INVALID = 'Fragmentation 必须在 256~2346';
var WIRELESSCONF_EXTENDSETUP_DYN_BLANKED = '请输入动态的信道';
var WIRELESSCONF_EXTENDSETUP_DYN_INVALID = '动态信道时间必须为 1~100';

var WIRELESSCONF_DISCONN_ALERT = '当前连接的设置页面的无线网络.\n如果继续安装, 将断开无线网络.\n您继续设置吗?';
</script>
