/*
** Copyright (c) 2009-2013 by Silicon Laboratories
**
** $Id: si_voice_version.c,v 1.1.1.1 2015/01/14 09:44:09 mt7620 Exp $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "7.0.0";
