<script>
var EXPERTCONF_DDNS_DELCONFIRM = "您要刪除DDNS設定嗎?";
var EXPERTCONF_DDNS_ADDSTR = "DDNS新增中..";
var EXPERTCONF_DDNS_DELSTR = "DDNS刪除中..";
var EXPERTCONF_DDNS_REFRESHSTR = "DDNS重新整理中..";
var EXPERTCONF_DDNS_HOSTNAMECHECK = "請輸入網域名稱";
var EXPERTCONF_DDNS_USERIDCHECK = "請輸入使用者名稱";
var EXPERTCONF_DDNS_CAPTCHACHECK = "請輸入密碼";
var DDNS_HOSTNAME_RULE_TXT="錯誤的DDNS網域名稱";
var SYSCONF_LOGIN_NEED_CAPTCHA_CODE="請填寫驗證碼";
var EXPERTCONF_DDNS_HOSTNAME_IS_BLANK ="請輸入主機名稱";
var EXPERTCONF_IPTIMEDNS_NOMORE_WANRING1 ="沒有更多的IPTIME DDNS主機";
var EXPERTCONF_DDNS_HOSTNAME_NOT_IPTIMEORG ="主機名稱須以iptime.org結尾";
var EXPERTCONF_IPTIMEDDNS_INVALID_USERID="只有E-mail位址有用";
var EXPERTCONF_DYNDNS_NOMORE_WANRING1="?有更多的DDNS主机";
var MSG_BLANK_ACCOUNT="請輸入使用者名稱";
var MSG_BLANK_PASSWORD="請輸入密碼";
</script>
