<script>
var EXPERTCONF_PPTPVPN_VPN_ACCOUNT_IS_BLANK="請輸入VPN帳號";
var EXPERTCONF_PPTPVPN_VPN_PASSWORD_IS_BLANK="請輸入VPN密碼";
var EXPERTCONF_PPTPVPN_IP_ADDRESS_IS_INVALID="請輸入IP位址";
var EXPERTCONF_PPTPVPN_DO_YOU_WANT_DELETE="是否刪除帳號?";
var EXPERTCONF_PPTPVPN_IPADDR_OVERLAP="IP位址已被使用";
var EXPERTCONF_PPTPVPN_ACCOUNT_OVERLAP="VPN帳號已被使用";

var EXPERTCONF_PPTPVPN_APPLYSTR = '執行中...';
var EXPERTCONF_PPTPVPN_DISCONNSTR = '選取使用者中斷中..';
var EXPERTCONF_PPTPVPN_DELETESTR = '選取使用者刪除中';
var EXPERTCONF_PPTPVPN_ADDSTR = '使用者新增中..';
var EXPERTCONF_PPTPVPN_NOSELECT = '無選取項目';
</script>
