<script>
var NETCONF_WANSETUP_APPLYSTR = '套用中...';
var NETCONF_WANSETUP_CONNSTR = '連線中...';
var NETCONF_WANSETUP_DISCONNSTR = '中斷連線中...';


var NETCONF_INTERNET_DHCP_MTU_INVALID="MTU值不可超過1500";
var NETCONF_INTERNET_PPP_MTU_INVALID="MTU值不可超過1492";
var NETCONF_INTERNET_KEEP_ALIVE_MSG="最大閒置時間錯誤";
var NETCONF_INTERNET_GW_INVALID_NETWORK="預設閘道與內部網路相同";
var NETCONF_WANSETUP_CONFIRM_WANINFO="確認變更WAN設定？";
</script>
