<script language="javascript" type="text/javascript">

var WIRELESSCONF_BASICSETUP_AUTOCHANNEL_STRING = '自動';
var WIRELESSCONF_BASICSETUP_UPPERCHANNEL = 'Lower';
var WIRELESSCONF_BASICSETUP_LOWERCHANNEL = 'Upper';
var WIRELESSCONF_BASICSETUP_TITLESTR = '選擇無線網路';
var WIRELESSCONF_BASICSETUP_DEFNET = '無線網路設定';
var WIRELESSCONF_BASICSETUP_GSTNET = '訪客網路';
var WIRELESSCONF_BASICSETUP_WPSCONNBTN = 'WPS';
var WIRELESSCONF_BASICSETUP_SECOND = '秒';

var WIRELESSCONF_WPSSETUP_PROCESSING = '請按無線設備上的WPS按鈕';
var WIRELESSCONF_WPSSETUP_CONFIGURED = '連線成功';

var WIRELESSCONF_BASICSETUP_SSID_BLANK = '請輸入無線網路名稱';
var WIRELESSCONF_BASICSETUP_SSID_OVERFLOW = '無線網路名稱過長\n非ascii字元為3bytes\n目前無線網路名稱長度: ';
var WIRELESSCONF_BASICSETUP_SSID_UNPERMITTED = '無線網路名稱含有不允許的特殊字元';
var WIRELESSCONF_BASICSETUP_RADIUSSERVER_INVALID = '請輸入正確的RADIUS伺服器IP';
var WIRELESSCONF_BASICSETUP_RADIUSPORT_INVALID = '請輸入正確的RADIUS連接埠';
var WIRELESSCONF_BASICSETUP_RADIUSSECRET_INVALID = '請輸入RADIUS密碼';
var WIRELESSCONF_BASICSETUP_WPAPSK_BLANKED = '請輸入金鑰密碼';
var WIRELESSCONF_BASICSETUP_WPAPSK_INVALID = '金鑰密碼至少需要輸入8個字元';
var WIRELESSCONF_BASICSETUP_WPAPSK_HEX_INVALID = '如果密碼輸入64個字元，\n則密碼需為十六進制字串';
var WIRELESSCONF_BASICSETUP_RXRATE_INVALID = '接收速率錯誤';
var WIRELESSCONF_BASICSETUP_TXRATE_INVALID = '傳送速率錯誤';
var WIRELESSCONF_BASICSETUP_REGULATION_WARNING = '';
var WIRELESSCONF_BASICSETUP_WEP_NOTSUPPORT = 'WEP加密強度不足';

var WIRELESSCONF_EXTENDSETUP_TXPOWER_BLANKED = '請輸入無線功率';
var WIRELESSCONF_EXTENDSETUP_TXPOWER_INVALID = '無線功率數值為1~100';
var WIRELESSCONF_EXTENDSETUP_BEACON_BLANKED = '請輸入Beacon';
var WIRELESSCONF_EXTENDSETUP_BEACON_INVALID = 'Beacon數值為50~1024';
var WIRELESSCONF_EXTENDSETUP_RTS_BLANKED = '請輸入RTS臨界值';
var WIRELESSCONF_EXTENDSETUP_RTS_INVALID = 'RTS臨界數值為0~2347';
var WIRELESSCONF_EXTENDSETUP_FRAG_BLANKED = '請輸入Fragmentation臨界值';
var WIRELESSCONF_EXTENDSETUP_FRAG_INVALID = 'Fragmentation臨界數值為256~2346';
var WIRELESSCONF_EXTENDSETUP_DYN_BLANKED = '請輸入動態頻道';
var WIRELESSCONF_EXTENDSETUP_DYN_INVALID = 'D動態頻道週期為1~100';

var WIRELESSCONF_DISCONN_ALERT = '目前使用無線網路連接設定頁面。\n如繼續設定將中斷無線網路。\n確定要繼續嗎？';
</script>
