#
# libposix makefile
# $Id: Makefile,v 1.1.1.1 2003/04/25 03:30:17 ken Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

