#ifndef __DIAG_STRING_H
#define __DIAG_STRING_H

#ifdef DIAG_ENGLISH_STRING 

#define DIAG_STRING_START "START DIAGNOSTICS"
#define DIAG_STRING_PASSED "TEST PASSED !!!!!!!!"
#define DIAG_STRING_MAC_ADDRESS "MAC ADDRESS"
#define DIAG_STRING_PASS_DESC0 "The system will be reloaded automatically"
#define DIAG_STRING_PASS_DESC1 "The Diagnostics will NOT be executed in next time"
#define DIAG_STRING_ERROR_DESC0 "TEST ERROR !!!!!!!!"
#define DIAG_STRING_ERROR_DESC1 "Repaire the system and try again"
#define DIAG_STRING_ERROR_DESC2 "The Diagnostics will be executed in next time"
#define DIAG_STRING_ERROR_DESC3 "System Halted"

#define DIAG_STRING_TEST_OK "OK"
#define DIAG_STRING_TEST_ERROR "ERROR"

#define DIAG_STRING_FLASH_START   "START FLASH MEMORY DIAGNOSTICS"
#define DIAG_STRING_FLASH_ERROR01 "NO FLASH FOUND"  
#define DIAG_STRING_FLASH_ERROR_ADDR  "ADDR"
#define DIAG_STRING_FLASH_ERROR_WDATA "WDATA"
#define DIAG_STRING_FLASH_ERROR_RDATA "RDATA"

#define DIAG_STRING_FLASH_DATA_TEST "DATA WRITE TEST"

#define DIAG_STRING_PORT_START     "START PORT DIAGNOSTICS"
#define DIAG_STRING_PORT_DATA_TEST "DATA TEST"
#define DIAG_STRING_PORT_ERROR01   "LINK FAIL"
#define DIAG_STRING_PORT_SUCCESS01 "TIME"
#define DIAG_STRING_PORT_ERROR02   "SEND ERROR"
#define DIAG_STRING_PORT_ERROR03   "RECV TIMEOUT"
#define DIAG_STRING_PORT_ERROR04   "CRC ERROR"
#define DIAG_STRING_PORT_ERROR05   "DATA ERROR"


#define DIAG_STRING_RESET_START   "RESET BUTTON DIAGNOSTICS"
#define DIAG_STRING_RESET_DESC0   "PRESS RESET BUTTON"
#define DIAG_STRING_RESET_TIMEOUT   "TIMEOUT"


#define DIAG_STRING_WIRELESS_START "START WIRELESS DIAGNOSTICS"
#define DIAG_STRING_WIRELESS_DETECT "WIRELESS MODULE DETECTION"
#define DIAG_STRING_WIRELESS_DETECTED "DETECTED"
#define DIAG_STRING_WIRELESS_NOT_DETECTED "NOT DETECTED"
#define DIAG_STRING_WIRELESS_WAITING "WAITING FOR WIRELESS CLIENT"
#define DIAG_STRING_WIRELESS_CLIENT_NOT_FOUND "CLIENT NOT FOUND"
#define DIAG_STRING_WIRELESS_CLIENT_FOUND "CLIENT FOUND"
#define DIAG_STRING_WIRELESS_DATA_TEST "WIRELESS DATA TEST"

#define DIAG_STRING_WIRELESS_TEST_01 "TIME=%d TX=%d RX=%d LOSS=%d"

#define DIAG_MAC_ADDRESSS_SET	"SET MAC ADDRESS ----------------------->\n"
#define DIAG_COMPANY_NAME	"COMPANY NAME"
#define DIAG_PRODUCT_NAME	"PRODUCT NAME"
#define DIAG_LANGUAGE		"LANGUAGE"
#define DIAG_MAC_ERROR		"ERROR: Invalid MAC Address: "
#define DIAG_CHECK_MAC		"Please check mac address & company information.."
#define DIAG_MAC_OK		"MAC Address is OK!!"
#define DIAG_SAVING_MAC		"Saving MAC Address .. "
#define DIAG_SAVING_END		"Completed"
#define DIAG_TYPE_MAC_ADDRESSS  "Type MAC address "



#endif

#ifdef DIAG_CHINESE_STRING

#define DIAG_STRING_START "开始测试"
#define DIAG_STRING_PASSED "测试已通过 !!!!!!!!"
#define DIAG_STRING_MAC_ADDRESS "MAC 地址"
#define DIAG_STRING_PASS_DESC0 "系统将会自动重启！"
#define DIAG_STRING_PASS_DESC1 "测试程序将不会再次执行！"
#define DIAG_STRING_ERROR_DESC0 "测试到错误!!!!!!!!"
#define DIAG_STRING_ERROR_DESC1 "请修复路由器后再测试一次！"
#define DIAG_STRING_ERROR_DESC2 "测试程序将会再次执行！"
#define DIAG_STRING_ERROR_DESC3 "系统已终止！"

#define DIAG_STRING_TEST_OK "OK"
#define DIAG_STRING_TEST_ERROR "错误"

#define DIAG_STRING_FLASH_START   "开始测试Flash"
#define DIAG_STRING_FLASH_ERROR01 "没有找到Flash"  

#define DIAG_STRING_FLASH_ERROR_ADDR  "地址"
#define DIAG_STRING_FLASH_ERROR_WDATA "写数据"
#define DIAG_STRING_FLASH_ERROR_RDATA "读数据"

#define DIAG_STRING_FLASH_DATA_TEST "数据写入测试"

#define DIAG_STRING_PORT_START     "开始测试端口"
#define DIAG_STRING_PORT_DATA_TEST "数据测试"
#define DIAG_STRING_PORT_ERROR01   "链接失败"
#define DIAG_STRING_PORT_SUCCESS01 "时间"
#define DIAG_STRING_PORT_ERROR02   "发送错误"
#define DIAG_STRING_PORT_ERROR03   "接收超时"
#define DIAG_STRING_PORT_ERROR04   "CRC错误"
#define DIAG_STRING_PORT_ERROR05   "数据错误"


#define DIAG_STRING_RESET_START   "复位按钮测试"
#define DIAG_STRING_RESET_DESC0   "按复位按钮"
#define DIAG_STRING_RESET_TIMEOUT   "超时"


#define DIAG_STRING_WIRELESS_START "开始无线测试"
#define DIAG_STRING_WIRELESS_DETECT "无线模块侦测"
#define DIAG_STRING_WIRELESS_DETECTED "已侦测到"
#define DIAG_STRING_WIRELESS_NOT_DETECTED "没有侦测到"
#define DIAG_STRING_WIRELESS_WAITING "等待无线客户端"
#define DIAG_STRING_WIRELESS_CLIENT_NOT_FOUND "客户端没找到"
#define DIAG_STRING_WIRELESS_CLIENT_FOUND "找到客户端"
#define DIAG_STRING_WIRELESS_DATA_TEST "无线数据测试"

#define DIAG_STRING_WIRELESS_TEST_TIME 	"时间"
#define DIAG_STRING_WIRELESS_TEST_TX 	"传输"
#define DIAG_STRING_WIRELESS_TEST_RX 	"接收"
#define DIAG_STRING_WIRELESS_TEST_LOSS 	"丢失"


#define DIAG_MAC_ADDRESSS_SET   "设置MAC 地址 ----------------------->\n"
#define DIAG_COMPANY_NAME       "公司名称"
#define DIAG_PRODUCT_NAME       "产品名称"
#define DIAG_LANGUAGE           "语言版本"
#define DIAG_MAC_ERROR          "警告: 错误的MAC 地址: "
#define DIAG_CHECK_MAC          "请确认MAC 地址和公司信息.."
#define DIAG_MAC_OK             "MAC 地址OK!!"
#define DIAG_SAVING_MAC         "保存MAC 地址中 .. "
#define DIAG_SAVING_END         "完成"
#define DIAG_TYPE_MAC_ADDRESSS	"输入MAC 地址"



#endif


#endif
