#define DCS_CHANNEL_CHANGED_MSG "무선 채널이 %d 번에서 %d 번으로 변경되었습니다.[동적채널변경]"
#define LIB_DDNS_BAD_AUTH                       "사용자 이름 또는 암호 오류"
#define LIB_DDNS_BLOCKED                        "클라이언트 접속 차단됨"
#define LIB_DDNS_CONN_FAIL              "연결 실패"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT     "Active 되어 있지 않음"
#define LIB_DDNS_DDNS_ERROR             "DNS 오류"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED   "지원되지 않는 Domain"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE   "등록이 차단된 호스트이름"
#define LIB_DDNS_HOSTNAME_NOT_EXIST     "등록되지 않은 호스트이름"
#define LIB_DDNS_NOT_YOURS              "다른 사용자의 호스트이름"
#define LIB_DDNS_ONLY_ONE_DOMAIN         "다른 호스트이름이 등록되어 있음."
#define LIB_DDNS_PARAMETER_INVALID      "매개변수 오류"
#define LIB_DDNS_SERVER_SHUTDOWN                "서버가 동작하지 않음"
#define LIB_DDNS_SUCCESS                        "정상 등록"
#define LIB_DDNS_TOO_MANY_OR_FEW                "호스트들의 갯수 오류"
#define LIB_DDNS_UNKNOWN_ERROR          "알수없는 오류"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR  "기부자가 아님"
#define LOGIN_LOG_WRITE_FAIL "IP : %s LOGIN 실패"
#define LOGIN_LOG_WRITE_TRUE "IP : %s LOGIN 성공"
#define SMTP_MESSAGE_STRING "SMTP Message"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "DHCP갱신시 게이트웨이 주소 변경 [ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "DHCP 갱신시 IP주소 변경 [ %s(%s) -> %s(%s) ]"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "설정 파일이 잘못되어 설정 복원 실패 - 파일 이름 : "
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "설정 복원 실패 - 파일 이름 : 입력되지 않음"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "설정 복원 성공 - 파일 이름 : "
#define SYSLOG_CUPSD_TITLE "네트워크 프린터 서버"
#define SYSLOG_DDNS_SERVER_CONNECTED "DDNS 서버에 접속됨" 
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "WAN%d 포트의 물리적 링크가 재연결 되어 DHCP기능을 다시 시작 합니다."
#define SYSLOG_DYN_IP                            "동적 IP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "관리자 E-mail 을 보내기 실패(연결 시간 초과) "
#define SYSLOG_EMAIL_SUBJECT "SYSLOG Report"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "관리자 E-mail 설정이 잘못됨"
#define SYSLOG_IP_CONFLICT "IP가 충돌이 감지되었습니다"
#define SYSLOG_LOG_CONTENT  "로그 내용"
#define SYSLOG_LOG_HISTORY "시스템 로그 이력"
#define SYSLOG_LOG_TIME  "발생시간"
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"관리자가 내부 IP를 변경함"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"관리자가 로그인 암호 변경"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"관리자가 링크설정을 변경"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"관리자가 인터넷 설정을 변경함"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "관리자가 인터넷을 연결함"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "관리자가 인터넷을 해제함"
#define SYSLOG_MSG_ADMIN_RESTART		"관리자가 시스템을 재시작함"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"관리자가 DHCP 서버를 실행함"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"관리자가 DHCP 서버를 중지함"
#define SYSLOG_MSG_AUTOREBOOT "자동 재시작 기능에 의하여 공유기가 자동으로 재시작됩니다."
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "기본 분산 경로가 변경됨"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "관리자가 무선 WAN 설정을 변경함"
#define SYSLOG_MSG_CSRF_BLOCK "악성 스크립트 접근 감지 (CSRF): "
#define SYSLOG_MSG_DDNS_FAILED			"DDNS 등록 실패"
#define SYSLOG_MSG_DDNS_SUCCESS			"DDNS 등록 성공"
#define SYSLOG_MSG_DHCPC_LEASE "외부 IP 대여시간 초과: 인터넷 끊김" 
#define SYSLOG_MSG_DHCPC_RCV_IP                 "DHCP Client가 IP를 받음"
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT         "DHCP Server 응답없음"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"DHCP 서버가 IP 할당함"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "내부네트워크에서 DHCP서버가 발견되지않아, 공유기의 DHCP서버 기능을 다시 실행함"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "내부네트워크에서 다른 DHCP서버가 검색되어 공유기의 DHCP서버 기능을 중단함"
#define SYSLOG_MSG_DNS_APPLY "%s에서 접속한 관리자가 DNS설정을 %s,%s로 변경하였습니다."
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"SMTP 게정 인증 실패 - 인증방법:"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          	"NETDETECT 관련 보고서를 관리자 E-mail 로 보냄"
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "SMTP 서버를 찾을 수 없어서 E-mail보내기 실패" 
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "SYSLOG 관련 보고서를 관리자 E-mail 로 보냄"
#define SYSLOG_MSG_FAKEDNS_START 	"관리자가 '설정 화면 자동연결' 기능 설정함"
#define SYSLOG_MSG_FAKEDNS_STOP 	"관리자가 '설정 화면 자동연결' 기능 해제함"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"관리자가 펌웨어를 업그레이드 함"
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"PPP계정 및 암호가 잘못됨"
#define SYSLOG_MSG_IPCONFLICT  "IP 충돌 감지 :" 
#define SYSLOG_MSG_KAID_AUTH_ERROR "PSP-KAI auth error(1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI download error(1)"
#define SYSLOG_MSG_KAID_RESTARTED "KAI 엔진이 재시작 되었습니다."
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "메일 서버에 연결할 수 없어서 메일 보내기 실패"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "메일 서버를 찾을 수 없어서 메일 보내기 실패"
#define SYSLOG_MSG_MAKE_SCHED_1 "인터넷을 사용하기 위해서는 공유기관리자에게 문의하셔야 합니다."
#define SYSLOG_MSG_MAKE_SCHED_2 "지금은 인터넷을 사용할 수 없는 시간입니다."
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS] 마스터 AP의 채널이 변경되었습니다."
#define SYSLOG_MSG_MASTER_AP_FOUND "마스터 AP 검색 성공"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "마스터 AP 검색 실패"
#define SYSLOG_MSG_NAT_OFF	"관리자가 NAT기능을 끔"
#define SYSLOG_MSG_NAT_ON	"관리자가 NAT기능을 킴"
#define SYSLOG_MSG_NO_MASTER_BEACON "마스터 AP로의 WDS연결이 끊김"
#define SYSLOG_MSG_PPP_CONNECTED		"PPP가 연결되어 IP를 받음"
#define SYSLOG_MSG_PPP_DISCONNECTED		"PPP연결이 끊어짐"
#define SYSLOG_MSG_PPP_NO_REPONSE		"PPPoE 서버의 응답이 없음"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "USB프린터가 인식되었습니다."
#define SYSLOG_MSG_RESTART			"시스템 재시작 ( Version: %s )"
#define SYSLOG_MSG_SAVECONF 	"모든 설정이 저장됨 "
#define SYSLOG_MSG_UPNP_START 	"관리자가 UPNP를 시작함(시스템 재시작)"
#define SYSLOG_MSG_UPNP_STOP 	"관리자가 UPNP를 중지함"
#define SYSLOG_MSG_WAN1_FAIL	"WAN1 인터넷 연결 끊김. WAN2로 백업"
#define SYSLOG_MSG_WAN1_OK	"WAN1 인터넷 연결 복원"
#define SYSLOG_MSG_WAN2_FAIL	"WAN2 인터넷 연결 끊김. WAN1로 백업"
#define SYSLOG_MSG_WAN2_OK	"WAN2 인터넷 연결 복원"
#define SYSLOG_MSG_WPS_FAIL	"WPS 무선 장치 연결 실패 [Error Code:%d]"
#define SYSLOG_MSG_WPS_OK	"WPS 무선 장치 연결 성공"
#define SYSLOG_NASCONF_AFP_RUN   "서비스"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Apache서버"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "Cloud백업 서비스"
#define SYSLOG_NASCONF_FTP_TITLE       "ipDISK/FTP 서비스"
#define SYSLOG_NASCONF_ITUNES_TITLE "iTunes서버"
#define SYSLOG_NASCONF_MEDIA_TITLE "미디어서버"
#define SYSLOG_NASCONF_MYSQL_TITLE     "MySQL서버"
#define SYSLOG_NASCONF_SAMBA_TITLE     "윈도우 파일공유 서비스"
#define SYSLOG_NASCONF_TORRENT_TITLE "토렌트"
#define SYSLOG_NASCONF_URL_TITLE       "URL서비스"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED "설정된 폴더의 하드디스크가 발견되지 않아 %s를(을) 중단합니다."
#define SYSLOG_NAS_SERVICE_STARTED 	"%s가(이) 시작되었습니다."
#define SYSLOG_NAS_SERVICE_STOPPED "%s가(이) 중단되었습니다."
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s이(가) 설치되어 있지 않기 때문에  서비스를 중단합니다."
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s 새 버전이 발견되어 업그레이드 하였습니다."
#define SYSLOG_PPPOE                             "PPPoE 방식"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "PPPoE 스케줄러에 의하여 연결이 복구됨: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "PPPoE 스케줄러에 의하여 연결이 중지됨: %s"
#define SYSLOG_PPTP                	         "PPTP IP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN 접속 성공 - 계정 : %s , 접속IP : %s" 
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN 접속 끊김 - 계정 : " 
#define SYSLOG_PRIVATE_IP_ASSIGN "WAN 포트에서 사설IP(%s) 할당 시도"
#define SYSLOG_RECEIVE_INTERNAL_IP "내부 IP와 동일한 외부IP가 할당되어 인터넷 연결불가"
#define SYSLOG_RECEIVE_PRIVATE_IP "사설IP 차단기능으로 인하여 사설IP가 외부IP로 설정되지 않음"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "WAN 포트에서 내부 네트워크와 같은 대역의 IP(%s) 할당 시도"
#define SYSLOG_SAVE_FAILED "저장 공간이 부족하여 더이상의 설정을 저장할 수 없습니다."
#define SYSLOG_SMART_QOS_DEL	"Smart QoS : %s 삭제"
#define SYSLOG_SMART_QOS_NEW	"Smart QoS : %s 추가"
#define SYSLOG_STATIC_IP                         "고정 IP"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "USB테더링 장치의 연결이 해제되었습니다."
#define SYSLOG_USB_FIND_THERING_DEVICE  "USB테더링 장치와 연결되었습니다."
#define SYSLOG_USB_STORAGE_DETECTED "USB%d번포트에서  USB저장장치가 감지되었습니다."
#define SYSLOG_USB_STORAGE_MOUNT "USB%d번포트의 USB저장장치가 활성화 되었습니다."
#define SYSLOG_USB_STORAGE_REMOVED "USB%d번포트에 연결된 USB저장장치가 분리되었습니다."
#define SYSLOG_USB_STORAGE_UNMOUNT "USB%d번포트의 USB저장장치가 비활성화 되었습니다."
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "연결된 AP로 부터 무선 맥인증 설정을 업데이트 하였습니다."
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "연결된 AP로 부터 무선 스케줄러 설정을 업데이트 하였습니다."
#define SYSLOG_WIFI_SCHED_START_WIFI "[무선스케줄러] %s 무선 기능을 재시작하였습니다."
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[무선스케줄러] %s 무선 기능을 중단하였습니다."
