#define DCS_CHANNEL_CHANGED_MSG "動態頻道搜尋已將通道由%d改為%d"
#define LIB_DDNS_BAD_AUTH                 "登入失敗(使用者名稱或密碼)"
#define LIB_DDNS_BLOCKED                  "連線已被阻擋"
#define LIB_DDNS_CONN_FAIL                "連線失敗"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "手動設定DNS伺服器未啟用"
#define LIB_DDNS_DDNS_ERROR               "DNS錯誤"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "請提供已認證網域"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "網域名稱因濫用被阻擋"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "網域名稱不存在"
#define LIB_DDNS_NOT_YOURS                "網域名稱非使用者擁有"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "網域名稱已被註冊"
#define LIB_DDNS_PARAMETER_INVALID        "參數無效"
#define LIB_DDNS_SERVER_SHUTDOWN          "伺服器關閉"
#define LIB_DDNS_SUCCESS                  "更新成功"
#define LIB_DDNS_TOO_MANY_OR_FEW          "找到太多或太少主機"
#define LIB_DDNS_UNKNOWN_ERROR            "未知錯誤"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "使用者並非付費使用者"
#define LOGIN_LOG_WRITE_FAIL "IP : %s 登入失敗"
#define LOGIN_LOG_WRITE_TRUE "IP : %s 連線成功"
#define SMTP_MESSAGE_STRING "SMTP訊息"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "DHCP閘道位址在DHCP更新時已變更[ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "IP位址在DHCP更新時已變更"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "設置還原失敗 - 檔案名稱"
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "設置還原失敗 - 無檔案名稱"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "設置還原成功 - 檔案名稱"
#define SYSLOG_CUPSD_TITLE "Network Printer Server"
#define SYSLOG_DDNS_SERVER_CONNECTED "已成功連線至DDNS伺服器"
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "WAN%d已連線，DHCP用戶端重新啟用。"
#define SYSLOG_DYN_IP                            "DHCP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "SMTP連線: 逾時告警終止"
#define SYSLOG_EMAIL_SUBJECT "系統紀錄檔報告"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "管理員E-mail設定錯誤"
#define SYSLOG_IP_CONFLICT "IP衝突"
#define SYSLOG_LOG_CONTENT  "系統紀錄檔內容"
#define SYSLOG_LOG_HISTORY "系統紀錄檔歷史紀錄"
#define SYSLOG_LOG_TIME  "時間"
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"管理員變更區域網路(內部)IP"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"管理員變更使用者名稱及密碼"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"管理員變更連線(通訊埠)設定"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"管理員變更網路連線設定"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "管理員重連網際網路"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "管理員中斷網際網路"
#define SYSLOG_MSG_ADMIN_RESTART		"管理員發送重啟指令"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"管理員啟用DHCP伺服器"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"管理員停用DHCP伺服器"
#define SYSLOG_MSG_AUTOREBOOT "[自動定期重啟]功能重新啟動路由器"
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "主要WAN連接埠已變更"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "管理員變更WAM連接埠設定"
#define SYSLOG_MSG_CSRF_BLOCK "偵測惡意編碼(CSRF): "
#define SYSLOG_MSG_DDNS_FAILED			"DDNS註冊失敗"
#define SYSLOG_MSG_DDNS_SUCCESS			"DDNS註冊成功"
#define SYSLOG_MSG_DHCPC_LEASE "WAN IP租約逾時:網際網路中斷連線"
#define SYSLOG_MSG_DHCPC_RCV_IP			"DHCP用戶端已連線WAN"
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT		"WAN端DHCP伺服器無回應"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"DHCP伺服器發放IP"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "DHCP伺服器已恢復"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "DHCP伺服器暫停服務,因區域網路內偵測到其他DHCP伺服器"
#define SYSLOG_MSG_DNS_APPLY "管理員 (%s) 設置DNS為%s,%s。"
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"SMTP驗證失敗"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          "網路檢測日誌E-mail發送成功"
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "E-mail報告發送失敗:找不到SMTP伺服器"
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "系統紀錄檔E-mail發送成功"
#define SYSLOG_MSG_FAKEDNS_START 	"管理員啟用'自動連線設定-頁面'"
#define SYSLOG_MSG_FAKEDNS_STOP 	"管理員停用'自動連線設定-頁面'"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"管理員升級系統"
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"PPPoE連線帳號或密碼錯誤"
#define SYSLOG_MSG_IPCONFLICT  "IP衝突"
#define SYSLOG_MSG_KAID_AUTH_ERROR "PSP-KAI驗證錯誤(1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI下載錯誤(1)"
#define SYSLOG_MSG_KAID_RESTARTED "KAI Engine已重新啟動"
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "寄送郵件時無法連接郵件伺服器"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "寄送郵件時找不到郵件伺服器"
#define SYSLOG_MSG_MAKE_SCHED_1 "網際網路服務目前無法使用因已被排程阻擋"
#define SYSLOG_MSG_MAKE_SCHED_2 "如要使用網路網路，請聯絡網路管理員"
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS]主AP通道已變更"
#define SYSLOG_MSG_MASTER_AP_FOUND "成功找到主AP"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "無法找到主AP"
#define SYSLOG_MSG_NAT_OFF	"管理員停用NAT"
#define SYSLOG_MSG_NAT_ON	"管理員啟用NAT"
#define SYSLOG_MSG_NO_MASTER_BEACON "與主AP中斷連線"
#define SYSLOG_MSG_PPP_CONNECTED		"WAN端已連接PPPoE網路"
#define SYSLOG_MSG_PPP_DISCONNECTED		"PPPoE連線中斷"
#define SYSLOG_MSG_PPP_NO_REPONSE		"WAN端PPPoE伺服器無回應"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "已辨識USB印表機"
#define SYSLOG_MSG_RESTART			"系統已重新啟動( Version: %s)"
#define SYSLOG_MSG_SAVECONF 	"所有設定已儲存"
#define SYSLOG_MSG_UPNP_START 	"管理員啟用UPNP(系統重啟)"
#define SYSLOG_MSG_UPNP_STOP 	"管理員停用UPNP"
#define SYSLOG_MSG_WAN1_FAIL	"WAN1端連線中斷，已轉移至WAN2連線"
#define SYSLOG_MSG_WAN1_OK	"WAN1已連線"
#define SYSLOG_MSG_WAN2_FAIL	"WAN2端連線中斷，已轉移至WAN1連線"
#define SYSLOG_MSG_WAN2_OK	"WAN2已連線"
#define SYSLOG_MSG_WPS_FAIL	"新增WPS設備失敗"
#define SYSLOG_MSG_WPS_OK	"新增WPS設備成功"
#define SYSLOG_NASCONF_AFP_RUN   "Service"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Apache伺服器"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "雲端備份"
#define SYSLOG_NASCONF_FTP_TITLE     "FTP 服務"
#define SYSLOG_NASCONF_ITUNES_TITLE "iTunes伺服器"
#define SYSLOG_NASCONF_MEDIA_TITLE "媒體伺服器"
#define SYSLOG_NASCONF_MYSQL_TITLE     "MySQL伺服器"
#define SYSLOG_NASCONF_SAMBA_TITLE   "Windows檔案共享(SAMBA)"
#define SYSLOG_NASCONF_TORRENT_TITLE "Torrent"
#define SYSLOG_NASCONF_URL_TITLE     "網址 服務"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED "找不到已設定資料夾。 %s 服務已終止"
#define SYSLOG_NAS_SERVICE_STARTED      "%s已啟動 "
#define SYSLOG_NAS_SERVICE_STOPPED "%s已關閉"
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s 尚未安裝"
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s - 已偵測到新版並升級"
#define SYSLOG_PPPOE                             "PPPoE"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "PPPoE連線已依據PPPoE連線時間設定恢復: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "PPPoE連線已依據PPPoE連線時間設定停止: %s"
#define SYSLOG_PPTP                	         "VPN IP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN 已連線 - 帳號 : %s / %s"
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN 中斷 - 帳號 :"
#define SYSLOG_PRIVATE_IP_ASSIGN "隔離來自WAN端的虛擬IP(%s)發放"
#define SYSLOG_RECEIVE_INTERNAL_IP "網際網路連線錯誤:WAN IP範圍與內部網路相同"
#define SYSLOG_RECEIVE_PRIVATE_IP "虛擬IP網際網路連線已禁止"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "WAN IP與內部區域網路IP相同"
#define SYSLOG_SAVE_FAILED "已無設定空間。無法儲存更多設定資料"
#define SYSLOG_SMART_QOS_DEL    "Smart QoS : %s 已刪除"
#define SYSLOG_SMART_QOS_NEW    "Smart QoS : %s 已新增"
#define SYSLOG_STATIC_IP                         "固定IP"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "USB網路共享設備已離線"
#define SYSLOG_USB_FIND_THERING_DEVICE  "USB網路共享設備已連接"
#define SYSLOG_USB_STORAGE_DETECTED "已偵測到USB儲存空間(USB%d)"
#define SYSLOG_USB_STORAGE_MOUNT "USB儲存空間已啟用(USB%d)"
#define SYSLOG_USB_STORAGE_REMOVED "USB儲存空間已拔除(USB%d)"
#define SYSLOG_USB_STORAGE_UNMOUNT "USB儲存空間已停用(USB%d)"
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "無線MAC驗證設定已更新自連線AP"
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "無線排程設定已更新自連線AP"
#define SYSLOG_WIFI_SCHED_START_WIFI "[無線排程] %s 無線網路已恢復"
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[無線排程] %s 無線網路已停止"
