#define DCS_CHANNEL_CHANGED_MSG "信道已更改%d 到 %d 通过动态信道搜索."
#define LIB_DDNS_BAD_AUTH                 "错误授权（用户名或密码）"
#define LIB_DDNS_BLOCKED                  "客户端已被阻止"
#define LIB_DDNS_CONN_FAIL                "连接失败"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "自定义DNS域未激活"
#define LIB_DDNS_DDNS_ERROR               "DNS错误遇到"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "没有提供完全合格的域名"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "主机名被滥用，系统将会阻止"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "主机名不存在"
#define LIB_DDNS_NOT_YOURS                "主机名不是您的"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "另一个主机名注册已经"
#define LIB_DDNS_PARAMETER_INVALID        "参数无效"
#define LIB_DDNS_SERVER_SHUTDOWN          "服务器关闭"
#define LIB_DDNS_SUCCESS                  "更新好，成功"
#define LIB_DDNS_TOO_MANY_OR_FEW          "发现过多或少的主机"
#define LIB_DDNS_UNKNOWN_ERROR            "未知错误"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "用户不是供体"
#define LOGIN_LOG_WRITE_FAIL "IP : %s 登录失败 "
#define LOGIN_LOG_WRITE_TRUE "IP : %s 登录成功 "
#define SMTP_MESSAGE_STRING "SMTP邮件"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "在DHCP更新过程中更改了网关地址 [ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "在DHCP更新过程中更改了IP地址 [ %s(%s) -> %s(%s) ]"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "配置恢复失败 - 文件名 :"
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "配置恢复失败 - 无文件名"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "配置恢复成功 - 文件名 :"
#define SYSLOG_CUPSD_TITLE "Network Printer Server"
#define SYSLOG_DDNS_SERVER_CONNECTED "已成功连接到DDNS服务器."
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "通过广域网 DHCP客户端重新启动%d 链接状态."
#define SYSLOG_DYN_IP                            "DHCP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "SMTP 客户端: 超时报警终止"
#define SYSLOG_EMAIL_SUBJECT "系统日志报告"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "管理员电子邮件配置无效"
#define SYSLOG_IP_CONFLICT "IP 冲突"
#define SYSLOG_LOG_CONTENT  "系统日志内容"
#define SYSLOG_LOG_HISTORY "系统日志历史记录"
#define SYSLOG_LOG_TIME  "时间戳 "
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"管理员更改了局域网（内部）IP"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"管理员更改了用户名和密码"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"管理员更改了链接（端口）配置"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"管理员更改了广域网配置"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "管理员重新连接因特网"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "管理员断开因特网"
#define SYSLOG_MSG_ADMIN_RESTART		"管理员发出了重新启动命令"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"管理员启用DHCP服务器"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"管理员已关闭DHCP服务器"
#define SYSLOG_MSG_AUTOREBOOT "通过[自动定期重启]功能重启路由器"
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "主广域网已更改"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "管理员更改了广域网端口配置"
#define SYSLOG_MSG_CSRF_BLOCK "检测恶意脚本（CSRF）: "
#define SYSLOG_MSG_DDNS_FAILED			"DDNS注册失败"
#define SYSLOG_MSG_DDNS_SUCCESS			"DDNS注册成功"
#define SYSLOG_MSG_DHCPC_LEASE "广域网 IP租约超时：因特网已断开连接" 
#define SYSLOG_MSG_DHCPC_RCV_IP			"广域网由DHCP客户端连接" 
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT		"在广域网中没有来自DHCP服务器的响应"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"DHCP服务器提供IP"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "DHCP服务器已恢复"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "DHCP服务器已暂停，因为在局域网网络中检测到其他DHCP服务器"
#define SYSLOG_MSG_DNS_APPLY "管理员 (%s) dns设置为 %s,%s."
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"SMTP验证失败"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          "网络检测电子邮件报告已成功发送" 
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "电子邮件报告失败：找不到SMTP服务器"
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "系统日志电子邮件报告已成功发送" 
#define SYSLOG_MSG_FAKEDNS_START 	"管理员打开 '自动连接设置页'"
#define SYSLOG_MSG_FAKEDNS_STOP 	"管理员关闭 '自动连接设置页'"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"管理员升级了系统" 
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"PPPoE连接期间帐户或密码无效"
#define SYSLOG_MSG_IPCONFLICT  "IP 冲突 :"
#define SYSLOG_MSG_KAID_AUTH_ERROR "PSP-KAI 身份验证错误(1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI 下载错误(1)"
#define SYSLOG_MSG_KAID_RESTARTED "KAI引擎重新启动"
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "发送邮件时无法连接邮件服务器"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "发送邮件时找不到邮件服务器"
#define SYSLOG_MSG_MAKE_SCHED_1 "英特尔网服务现在不可用，因为它被计划阻止."
#define SYSLOG_MSG_MAKE_SCHED_2 "如果您要使用互联网，请询问您的网络管理员."
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS] 主AP的信道改变"
#define SYSLOG_MSG_MASTER_AP_FOUND "成功找到主AP"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "找不到主AP"
#define SYSLOG_MSG_NAT_OFF	"管理员关闭NAT" 
#define SYSLOG_MSG_NAT_ON	"管理员打开NAT" 
#define SYSLOG_MSG_NO_MASTER_BEACON "已与主AP断开"
#define SYSLOG_MSG_PPP_CONNECTED		"广域网通过PPPoE连接"
#define SYSLOG_MSG_PPP_DISCONNECTED		"PPPoE连接断开" 
#define SYSLOG_MSG_PPP_NO_REPONSE		"广域网中的PPPoE服务器没有响应"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "USB打印机被识别."
#define SYSLOG_MSG_RESTART			"系统重新启动( 版本: %s)"
#define SYSLOG_MSG_SAVECONF 	"所有配置都保存"
#define SYSLOG_MSG_UPNP_START 	"管理员开启UPNP（系统重新启动）" 
#define SYSLOG_MSG_UPNP_STOP 	"管理员关闭UPNP"
#define SYSLOG_MSG_WAN1_FAIL	"广域网1断开，并转移到广域网2"
#define SYSLOG_MSG_WAN1_OK	"广域网1 连接"
#define SYSLOG_MSG_WAN2_FAIL	"广域网2已断开连接，并转接到广域网1"
#define SYSLOG_MSG_WAN2_OK	"广域网2已连接"
#define SYSLOG_MSG_WPS_FAIL	"添加WPS设备失败. [错误代码:%d]"
#define SYSLOG_MSG_WPS_OK	"成功添加WPS设备."
#define SYSLOG_NASCONF_AFP_RUN   "Service"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Apache 服务器"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "云备份"
#define SYSLOG_NASCONF_FTP_TITLE     "FTP 服务"
#define SYSLOG_NASCONF_ITUNES_TITLE "iTunes 服务器"
#define SYSLOG_NASCONF_MEDIA_TITLE "媒体服务器"
#define SYSLOG_NASCONF_MYSQL_TITLE     "数据库服务器"
#define SYSLOG_NASCONF_SAMBA_TITLE   "Windows 文件共享(SAMBA)"
#define SYSLOG_NASCONF_TORRENT_TITLE "离线下载"
#define SYSLOG_NASCONF_URL_TITLE     "URL 服务"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED " 未找到已配置的文件夹 . %s 服务器停止."
#define SYSLOG_NAS_SERVICE_STARTED      "%s 启动." 
#define SYSLOG_NAS_SERVICE_STOPPED "%s 停止."
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s 未安装."
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s  - 检测和升级新版本."
#define SYSLOG_PPPOE                             "PPPoE"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "通过PPPoE调度程序恢复PPPoE连接: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "通过PPPoE调度程序停止PPPoE连接: %s"
#define SYSLOG_PPTP                	         "PPTP IP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN 连接 - 帐户 : %s / %s"
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN 断开 - 帐户 : "
#define SYSLOG_PRIVATE_IP_ASSIGN "隔离的私有IP (%s) 从广域网分配"
#define SYSLOG_RECEIVE_INTERNAL_IP "因特网连接错误：广域网 IP范围与内部网络相同."
#define SYSLOG_RECEIVE_PRIVATE_IP "互联网连接的私有IP被禁止"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "广域网 IP与内部局域网相同."
#define SYSLOG_SAVE_FAILED "无更多配置空间.不能存储更多的配置数据." 
#define SYSLOG_SMART_QOS_DEL    "智能 QoS : %s 删除"
#define SYSLOG_SMART_QOS_NEW    "智能 QoS : %s 添加"
#define SYSLOG_STATIC_IP                         "静态"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "USB 共享设备已断开."
#define SYSLOG_USB_FIND_THERING_DEVICE  "USB 共享设备已连接."
#define SYSLOG_USB_STORAGE_DETECTED "检测到USB存储.(USB%d)"
#define SYSLOG_USB_STORAGE_MOUNT "USB存储器已激活.(USB%d)"
#define SYSLOG_USB_STORAGE_REMOVED "USB存储器已断开连接.(USB%d)"
#define SYSLOG_USB_STORAGE_UNMOUNT "USB存储被禁用.(USB%d)"
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "无线MAC认证配置从连接的AP更新."
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "无线计划程序配置从已连接的AP更新."
#define SYSLOG_WIFI_SCHED_START_WIFI "[无线调度程序] %s 无线恢复."
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[无线调度程序] %s 无线停止."
