#define DCS_CHANNEL_CHANGED_MSG "Kênh truyền được thay đổi từ %d sang  %d bởi Tìm Kiếm Kênh Tự Động."
#define LIB_DDNS_BAD_AUTH                 "Lỗi truy cập (sai tên đăng nhập hoặc mật khẩu)"
#define LIB_DDNS_BLOCKED                  "Máy khách đã bị chặn"
#define LIB_DDNS_CONN_FAIL                "Kết nối thất bại"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "Tên miền DNS tùy chọn chưa được kích hoạt"
#define LIB_DDNS_DDNS_ERROR               "Gặp lỗi DNS"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "Không cung cấp tên miền Đủ Điều Kiện FQDN"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "Tên máy chủ bị chặn vì lạm dụng"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "Tên máy chủ không tồn tại"
#define LIB_DDNS_NOT_YOURS                "Tên máy chủ không phải của bạn"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "Một máy khác đã đăng ký"
#define LIB_DDNS_PARAMETER_INVALID        "Tham số không hợp lệ"
#define LIB_DDNS_SERVER_SHUTDOWN          "Tắt máy chủ"
#define LIB_DDNS_SUCCESS                  "Cập nhật thành công"
#define LIB_DDNS_TOO_MANY_OR_FEW          "Đã tìm thấy vài hoặc nhiều máy"
#define LIB_DDNS_UNKNOWN_ERROR            "Lỗi không xác định"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "Người dùng không phải là người hiến tặng"
#define LOGIN_LOG_WRITE_FAIL "IP : %s Đăng nhập lỗi"
#define LOGIN_LOG_WRITE_TRUE "IP : %s Đăng nhập thành công"
#define SMTP_MESSAGE_STRING "Thông báo SMTP"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "Địa chỉ Gateway đã thay đổi trong quá trình làm mới DHCP [ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "Địa chỉ IP đã thay đổi trong quá trình làm mới DHCP [ %s(%s) -> %s(%s) ]"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "Phục hồi cấu hình không thành công - tên tệp:"
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "Phục hồi cấu hình không thành công - không có tên tệp"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "Phục hồi cấu hình thành công - tên tệp:"
#define SYSLOG_CUPSD_TITLE "Mạng máy chủ máy in"
#define SYSLOG_DDNS_SERVER_CONNECTED "Đã kết nối thành công với máy chủ DDNS."
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "DHCP máy trạm được khởi động bởi trạng thái liên kết WAN%d."
#define SYSLOG_DYN_IP                            "DHCP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "Máy khách SMTP: Thông báo quá thời gian"
#define SYSLOG_EMAIL_SUBJECT "Báo cáo SYSLOG"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "Cấu hình E-mail Admin không hợp lệ"
#define SYSLOG_IP_CONFLICT "Cấu hình IP"
#define SYSLOG_LOG_CONTENT  "Nội dung nhật ký hệ thống"
#define SYSLOG_LOG_HISTORY "Lịch sử đăng nhập hệ thống"
#define SYSLOG_LOG_TIME  "Dấu thời gian"
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"Quản trị viên đã thay đổi địa chỉ IP LAN (Nội bộ)"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"Quản trị viên thay đổi tên người dùng và mật khẩu"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"Quản trị viên đã thay đổi cấu hình liên kết (cổng)"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"Quản trị viên đã thay đổi cấu hình WAN"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "Quản trị viên kết nối lại internet"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "Quản trị viên ngắt kết nối Internet"
#define SYSLOG_MSG_ADMIN_RESTART		"Quản trị viên thực hiện lệnh Restart"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"Quản trị viên đã bật máy chủ DHCP"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"Quản trị viên đã tắt máy chủ DHCP"
#define SYSLOG_MSG_AUTOREBOOT "Khởi động lại Router bằng chức năng [Tự khởi động lại theo chu kỳ]"
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "WAN chính đã thay đổi"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "Quản trị viên đã thay đổi cấu hình cổng wan"
#define SYSLOG_MSG_CSRF_BLOCK "Phát hiện tập lệnh độc hại (CSRF): "
#define SYSLOG_MSG_DDNS_FAILED			"Đăng ký DDNS không thành công"
#define SYSLOG_MSG_DDNS_SUCCESS			"Đăng ký DDNS thành công"
#define SYSLOG_MSG_DHCPC_LEASE "Thời gian thuê IP WAN hết hạn: Internet đã ngắt kết nối" 
#define SYSLOG_MSG_DHCPC_RCV_IP			"WAN được kết nối bởi DHCP máy khách" 
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT		"Không có phản hồi từ máy chủ DHCP trong WAN"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"Máy chủ DHCP cung cấp IP"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "Máy chủ DHCP đã tiếp tục lại"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "Máy chủ DHCP bị treo, vì đã được phát hiện máy chủ DHCP khác trong mạng LAN"
#define SYSLOG_MSG_DNS_APPLY "Admin (%s) cài DNS thành %s,%s."
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"Xác thực SMTP không thành công"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          "Phát hiện báo cáo E-mail đã gửi thành công" 
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "Báo cáo e-mail không thành công: Không thể tìm thấy máy chủ SMTP"
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "Đã gửi báo cáo SYSLOG E-mail thành công" 
#define SYSLOG_MSG_FAKEDNS_START 	"Quản trị viên bật 'Thiết lập kết nối tự động'"
#define SYSLOG_MSG_FAKEDNS_STOP 	"Quản trị viên tắt 'Thiết lập kết nối tự động'"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"Quản trị viên đã nâng cấp hệ thống" 
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"Tài khoản hoặc mật khẩu không hợp lệ trong quá trình kết nối PPPoE"
#define SYSLOG_MSG_IPCONFLICT  "IP xung đột:"
#define SYSLOG_MSG_KAID_AUTH_ERROR "Lỗi xác thực PSP-KAI (1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI tải về lỗi (1)"
#define SYSLOG_MSG_KAID_RESTARTED "Khởi động lại động cơ KAI"
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "Không thể kết nối máy chủ thư trong khi gửi thư"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "Không thể tìm thấy máy chủ thư trong khi gửi thư"
#define SYSLOG_MSG_MAKE_SCHED_1 "Dịch vụ Internet hiện không có sẵn vì nó được lên lịch chặn."
#define SYSLOG_MSG_MAKE_SCHED_2 "Nếu bạn muốn sử dụng internet, hãy hỏi người quản trị viên của bạn."
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS] Kênh Master AP đã bị thay đổi"
#define SYSLOG_MSG_MASTER_AP_FOUND "Tìm thành công Master AP"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "Không tìm thấy Master AP"
#define SYSLOG_MSG_NAT_OFF	"Quản trị viên tắt NAT" 
#define SYSLOG_MSG_NAT_ON	"Quản trị viên bật NAT" 
#define SYSLOG_MSG_NO_MASTER_BEACON "Đã ngắt kết nối với Master AP"
#define SYSLOG_MSG_PPP_CONNECTED		"WAN được kết nối bằng PPPoE"
#define SYSLOG_MSG_PPP_DISCONNECTED		"Kết nối PPPoE bị ngắt kết nối" 
#define SYSLOG_MSG_PPP_NO_REPONSE		"Không có phản hồi từ máy chủ PPPoE trong WAN"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "Máy in USB đã được công nhận."
#define SYSLOG_MSG_RESTART			"Hệ thống khởi động lại (Phiên bản: %s)"
#define SYSLOG_MSG_SAVECONF 	"Tất cả cấu hình được lưu"
#define SYSLOG_MSG_UPNP_START 	"Quản trị viên bật UPNP (Khởi động lại hệ thống)" 
#define SYSLOG_MSG_UPNP_STOP 	"Quản trị viên tắt UPNP"
#define SYSLOG_MSG_WAN1_FAIL	"WAN1 ngắt kết nối, và chuyển hướng tới WAN2"
#define SYSLOG_MSG_WAN1_OK	"Kết nối WAN1"
#define SYSLOG_MSG_WAN2_FAIL	"WAN2 ngắt kết nối và chuyển hướng tới WAN1"
#define SYSLOG_MSG_WAN2_OK	"Kết nối WAN2"
#define SYSLOG_MSG_WPS_FAIL	"Không thể thêm thiết bị WPS. [Mã lỗi: %d]"
#define SYSLOG_MSG_WPS_OK	"Thành công trong việc thêm thiết bị WPS."
#define SYSLOG_NASCONF_AFP_RUN   "Dịch vụ"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Máy chủ Apache"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "Cloud Backup"
#define SYSLOG_NASCONF_FTP_TITLE     "Dịch vụ FTP"
#define SYSLOG_NASCONF_ITUNES_TITLE "máy chủ iTunes"
#define SYSLOG_NASCONF_MEDIA_TITLE "Máy chủ Media"
#define SYSLOG_NASCONF_MYSQL_TITLE     "Máy chủ MySQL"
#define SYSLOG_NASCONF_SAMBA_TITLE   "Chia sẻ Tệp Windows (SAMBA)"
#define SYSLOG_NASCONF_TORRENT_TITLE "Torrent"
#define SYSLOG_NASCONF_URL_TITLE     "Dịch vụ URL"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED "Không tìm thấy thư mục được định cấu hình. Dịch vụ %s bị dừng."
#define SYSLOG_NAS_SERVICE_STARTED      "%s được khởi động." 
#define SYSLOG_NAS_SERVICE_STOPPED "%s đã tắt."
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s chưa được cài đặt."
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s - phiên bản mới được phát hiện và nâng cấp."
#define SYSLOG_PPPOE                             "PPPoE"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "Tiếp tục kết nối PPPoE theo lịch trình của PPPoE: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "Dừng kết nối PPPoE theo lịch trình của PPPoE: %s"
#define SYSLOG_PPTP                	         "IP PPTP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN Kết nối - Tài khoản: %s / %s"
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN Ngắt kết nối - Tài khoản: "
#define SYSLOG_PRIVATE_IP_ASSIGN "Cô lập địa chỉ IP(%s) nội bộ"
#define SYSLOG_RECEIVE_INTERNAL_IP "Lỗi kết nối Internet: Lớp IP WAN giống với lớp mạng nội bộ."
#define SYSLOG_RECEIVE_PRIVATE_IP "Địa chỉ IP riêng để kết nối internet bị chặn"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "IP WAN giống như mạng LAN nội bộ."
#define SYSLOG_SAVE_FAILED "Không còn không gian cấu hình. Không thể lưu trữ dữ liệu cấu hình." 
#define SYSLOG_SMART_QOS_DEL    "Smart QoS : %s đã xóa"
#define SYSLOG_SMART_QOS_NEW    "Smart QoS : %s được thêm"
#define SYSLOG_STATIC_IP                         "IP Tĩnh"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "Thiết bị tether USB bị ngắt kết nối."
#define SYSLOG_USB_FIND_THERING_DEVICE  "Thiết bị tether USB đã kết nối."
#define SYSLOG_USB_STORAGE_DETECTED "Đã phát hiện bộ lưu trữ USB (USB%d)"
#define SYSLOG_USB_STORAGE_MOUNT "Bộ lưu trữ USB được kích hoạt. (USB%d)"
#define SYSLOG_USB_STORAGE_REMOVED "Bộ lưu trữ USB bị ngắt kết nối (USB%d)"
#define SYSLOG_USB_STORAGE_UNMOUNT "Bộ lưu trữ USB lkhông hoạt động (USB% d)"
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "Cấu hình chứng thực MAC Wi-FI được cập nhật khi kết nối AP"
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "Cấu hình lập lịch Wi-FI được cập nhật khi kết nối AP."
#define SYSLOG_WIFI_SCHED_START_WIFI "[Lập lịch Wi-Fi] %s Wi-Fi mở"
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[Lập lịch Wi-Fi] %s Wi-Fi tắt"
