#define DCS_CHANNEL_CHANGED_MSG "Channel is changed from %d to %d by Dynamic Channel Searching."
#define LIB_DDNS_BAD_AUTH                 "Bad authorization(username or password)"
#define LIB_DDNS_BLOCKED                  "Client has been blocked"
#define LIB_DDNS_CONN_FAIL                "Connection fail"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "Custom DNS domain not activated"
#define LIB_DDNS_DDNS_ERROR               "DNS error encountered"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "Fully-Qualified Domain not provided"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "Hostname is blocked for abuse"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "Hostname not exists"
#define LIB_DDNS_NOT_YOURS                "Hostname is not yours"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "Another hostname registered already"
#define LIB_DDNS_PARAMETER_INVALID        "Parameter not valid"
#define LIB_DDNS_SERVER_SHUTDOWN          "Server shutdown"
#define LIB_DDNS_SUCCESS                  "Update good and successful"
#define LIB_DDNS_TOO_MANY_OR_FEW          "Too many or few hosts found"
#define LIB_DDNS_UNKNOWN_ERROR            "Unknown error"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "User is not a donator"
#define LOGIN_LOG_WRITE_FAIL "IP : %s LOGIN Fail"
#define LOGIN_LOG_WRITE_TRUE "IP : %s LOGIN Success"
#define SMTP_MESSAGE_STRING "SMTP Message"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "Gateway address was changed during DHCP renew process [ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "IP address was changed during DHCP renew process [ %s(%s) -> %s(%s) ]"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "Configuration recovery failed - filename :"
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "Configuration recovery failed - No filename"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "Configuration recovery success - filename :"
#define SYSLOG_CUPSD_TITLE "Network Printer Server"
#define SYSLOG_DDNS_SERVER_CONNECTED "Successfully connected to DDNS server."
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "DHCP client restarted by WAN%d link status."
#define SYSLOG_DYN_IP                            "DHCP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "SMTP client: Timeout Alarm Termination"
#define SYSLOG_EMAIL_SUBJECT "SYSLOG Report"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "Invalid Admin E-mail Configuration"
#define SYSLOG_IP_CONFLICT "IP Conflicting"
#define SYSLOG_LOG_CONTENT  "System Log Contents"
#define SYSLOG_LOG_HISTORY "System Log History"
#define SYSLOG_LOG_TIME  "Timestamp"
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"Administrator changed the LAN(Internal) IP"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"Administrator changed the username and the password"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"Administrator changed the link(port) configuration"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"Administrator changed the WAN configuration"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "Administrator reconnect the internet"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "Administrator disconnect the internet"
#define SYSLOG_MSG_ADMIN_RESTART		"Administrator issued the Restart command"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"Administrator turned on DHCP server"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"Administrator turned off DHCP server"
#define SYSLOG_MSG_AUTOREBOOT "Restart Router by [Auto Periodic Reboot] function"
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "Primary WAN changed"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "Administrator changed the wan port configuration"
#define SYSLOG_MSG_CSRF_BLOCK "Detect Malicious Script(CSRF): "
#define SYSLOG_MSG_DDNS_FAILED			"DDNS registration failed"
#define SYSLOG_MSG_DDNS_SUCCESS			"DDNS registration success"
#define SYSLOG_MSG_DHCPC_LEASE "WAN IP Lease Timeout: Internet Disconnected" 
#define SYSLOG_MSG_DHCPC_RCV_IP			"WAN is connected by DHCP client" 
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT		"No response from DHCP Server in WAN"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"DHCP Server offers IP"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "DHCP server was resumed"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "DHCP server was suspended ,because other DHCP server has been detected in LAN network"
#define SYSLOG_MSG_DNS_APPLY "Admin (%s) set dns to %s,%s."
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"SMTP Authentication Failed"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          "Netdetect E-mail report sent successfully" 
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "E-mail report failed:Can't find SMTP server"
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "SYSLOG E-mail report sent successfully" 
#define SYSLOG_MSG_FAKEDNS_START 	"Administrator turn on 'Auto Connecting Setup-Page'"
#define SYSLOG_MSG_FAKEDNS_STOP 	"Administrator turn off 'Auto Connecting Setup-Page'"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"Administrator upgraded the system" 
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"Invalid account or password during PPPoE connection"
#define SYSLOG_MSG_IPCONFLICT  "IP Confliction :"
#define SYSLOG_MSG_KAID_AUTH_ERROR "PSP-KAI auth error(1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI download error(1)"
#define SYSLOG_MSG_KAID_RESTARTED "KAI engine restarted"
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "Could not connect mail server while sending mail"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "Could not find mail server while sending mail"
#define SYSLOG_MSG_MAKE_SCHED_1 "Internet service is not available now because it is scheduled to block."
#define SYSLOG_MSG_MAKE_SCHED_2 "If you want to use internet, ask your network administrator."
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS] Master AP's Channel is changed"
#define SYSLOG_MSG_MASTER_AP_FOUND "Found Master AP successfully"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "Can't find Master AP"
#define SYSLOG_MSG_NAT_OFF	"Administrator turn off the NAT" 
#define SYSLOG_MSG_NAT_ON	"Administrator turn on the NAT" 
#define SYSLOG_MSG_NO_MASTER_BEACON "Disconnected with Master AP"
#define SYSLOG_MSG_PPP_CONNECTED		"WAN is connected by PPPoE"
#define SYSLOG_MSG_PPP_DISCONNECTED		"PPPoE connection disconnected" 
#define SYSLOG_MSG_PPP_NO_REPONSE		"No response from PPPoE server in WAN"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "USB Printer is recognized."
#define SYSLOG_MSG_RESTART			"System restarted ( Version: %s)"
#define SYSLOG_MSG_SAVECONF 	"All configruations are saved"
#define SYSLOG_MSG_UPNP_START 	"Administrator turn on UPNP(System restart)" 
#define SYSLOG_MSG_UPNP_STOP 	"Administrator turn off UPNP"
#define SYSLOG_MSG_WAN1_FAIL	"WAN1 disconnected, and diverted to WAN2"
#define SYSLOG_MSG_WAN1_OK	"WAN1 connected"
#define SYSLOG_MSG_WAN2_FAIL	"WAN2 disconnected, and diverted to WAN1"
#define SYSLOG_MSG_WAN2_OK	"WAN2 connected"
#define SYSLOG_MSG_WPS_FAIL	"Failed in adding WPS device. [Error Code:%d]"
#define SYSLOG_MSG_WPS_OK	"Success in adding WPS device."
#define SYSLOG_NASCONF_AFP_RUN   "Service"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Apache Server"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "Cloud Backup"
#define SYSLOG_NASCONF_FTP_TITLE     "FTP Service"
#define SYSLOG_NASCONF_ITUNES_TITLE "iTunes Server"
#define SYSLOG_NASCONF_MEDIA_TITLE "Media Server"
#define SYSLOG_NASCONF_MYSQL_TITLE     "MySQL Server"
#define SYSLOG_NASCONF_SAMBA_TITLE   "Windows File Sharing(SAMBA)"
#define SYSLOG_NASCONF_TORRENT_TITLE "Torrent"
#define SYSLOG_NASCONF_URL_TITLE     "URL Service"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED "The configured Folder is not found. %s service is stopped."
#define SYSLOG_NAS_SERVICE_STARTED      "%s is started." 
#define SYSLOG_NAS_SERVICE_STOPPED "%s is stopped."
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s is not installed."
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s - new version is detected & upgraded."
#define SYSLOG_PPPOE                             "PPPoE"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "Resume PPPoE connection by PPPoE scheduler: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "Stop PPPoE connection by PPPoE scheduler: %s"
#define SYSLOG_PPTP                	         "PPTP IP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN Connected - Account : %s / %s"
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN Disconnected - Account : "
#define SYSLOG_PRIVATE_IP_ASSIGN "Isolate private IP(%s) assignment from WAN"
#define SYSLOG_RECEIVE_INTERNAL_IP "Internet Connection Error:WAN IP range is the same as internal network's."
#define SYSLOG_RECEIVE_PRIVATE_IP "Private IP for internet connection is inhibited"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "WAN IP is the same as internal LAN's."
#define SYSLOG_SAVE_FAILED "No more configration space. No more config data can be stored." 
#define SYSLOG_SMART_QOS_DEL    "Smart QoS : %s deleted"
#define SYSLOG_SMART_QOS_NEW    "Smart QoS : %s added"
#define SYSLOG_STATIC_IP                         "Static"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "USB Tethering Device is disconnected."
#define SYSLOG_USB_FIND_THERING_DEVICE  "USB Tethering Device is connected."
#define SYSLOG_USB_STORAGE_DETECTED "USB Storage is detected.(USB%d)"
#define SYSLOG_USB_STORAGE_MOUNT "USB Storage is activated.(USB%d)"
#define SYSLOG_USB_STORAGE_REMOVED "USB Storage is disconnected.(USB%d)"
#define SYSLOG_USB_STORAGE_UNMOUNT "USB Storage is deactivated.(USB%d)"
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "Wireless MAC Authentication Configuration is updated from connected AP."
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "Wireless Scheduler Configuration is updated from connected AP."
#define SYSLOG_WIFI_SCHED_START_WIFI "[Wireless Scheduler] %s wireless is resumed."
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[Wireless Scheduler] %s wireless is stopped."
