#ifdef USE_NETDETECT
#define LATEST_TIME     	"最新检测时间"
#define IPADDRESS       	"IP 地址"
#define PROTOCOL        	"协议"
#define FREQUENCY       	"频率"
#define COMMENT         	"注释 [红色:用户警告关闭]"

#define VIRUS_COMMENT   	"可能感染了蠕虫病毒"
#define EMAIL_COMMENT   	"可能感染了电子邮件病毒" 
#define HTTP_COMMENT    	"突发网络连接或检查病毒"
#define SORIBADA_COMMENT	"检测到Soribada"
#define EDONKEY_COMMENT	 	"检测到e-donkey"
#define VSHARE_COMMENT  	"检测到V-Share"
#define WINMX_COMMENT    	"检测到WinMX"
#define FILEGURI_COMMENT    	"检测到FileGuri"
#define KAZAA_COMMENT     	"检测到KaZaA"
#define BATTLENET_COMMENT     	"检测到Battle Net"
#define OTHERS_COMMENT    	"检测到未知端口.注意"
#endif

#define LIB_NETCONF_WIRELESS_KOREA                  "韩国"
#define LIB_NETCONF_WIRELESS_EU                     "欧洲"
#define LIB_NETCONF_WIRELESS_CHINA                  "中国"
#define LIB_NETCONF_WIRELESS_USA                    "美国，加拿大"
#define LIB_NETCONF_WIRELESS_JAPAN                  "日本"
#define LIB_NETCONF_WIRELESS_OTHERS                 "其它"
