#ifdef USE_NETDETECT
#define LATEST_TIME     	"Latest Detection Time"
#define IPADDRESS       	"IP Address"
#define PROTOCOL        	"Protocol"
#define FREQUENCY       	"Frequency"
#define COMMENT         	"Comment [Red:User Warning OFF]"

#define VIRUS_COMMENT   	"Probably infected with Worm Virus"
#define EMAIL_COMMENT   	"Probably infected with E-Mail Virus" 
#define HTTP_COMMENT    	"Burst WEB connection or check Virus"
#define SORIBADA_COMMENT	"Soribada detected"
#define EDONKEY_COMMENT	 	"e-Donkey detected"
#define VSHARE_COMMENT  	"V-Share detected"
#define WINMX_COMMENT    	"WinMX detected"
#define FILEGURI_COMMENT    	"FileGuri detected"
#define KAZAA_COMMENT     	"KaZaA detected"
#define BATTLENET_COMMENT     	"Battle Net detected"
#define OTHERS_COMMENT    	"Unknown Port detected. Watch out"
#endif

#define LIB_NETCONF_WIRELESS_KOREA "大韓民国"
#define LIB_NETCONF_WIRELESS_CHINA "中国"
#define LIB_NETCONF_WIRELESS_USA "アメリカ"
#define LIB_NETCONF_WIRELESS_JAPAN "日本"
#define LIB_NETCONF_WIRELESS_EU "その他"
#define LIB_NETCONF_WIRELESS_OTHERS "その他"

#define LIB_DDNS_SUCCESS "正常登録"
#define LIB_DDNS_BAD_AUTH "ユーザー名又はパスワード誤"
#define LIB_DDNS_PARAMETER_INVALID "媒介変数誤謬"
#define LIB_DDNS_BLOCKED "クライアント接続遮断"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED "支援しないドメイン"
#define LIB_DDNS_HOSTNAME_NOT_EXIST "登録されてないホスト名"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR "寄付者ではない"
#define LIB_DDNS_NOT_YOURS "他のユーザーのホスト名"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT "Active されていない"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE "道路区が遮断されているホスト名"
#define LIB_DDNS_TOO_MANY_OR_FEW "ホスト達の数が正確ではない"
#define LIB_DDNS_DDNS_ERROR "DNS 誤謬"
#define LIB_DDNS_SERVER_SHUTDOWN "サーバーが動作しない"

#define LIB_DDNS_CONN_FAIL "接続失敗"
#define LIB_DDNS_ONLY_ONE_DOMAIN "他のホスト名が登録されています。"
#define LIB_DDNS_UNKNOWN_ERROR "知らせていない誤謬"

