#ifdef USE_NETDETECT
#define LATEST_TIME     	"Latest Detection Time"
#define IPADDRESS       	"IP Address"
#define PROTOCOL        	"Protocol"
#define FREQUENCY       	"Frequency"
#define COMMENT         	"Comment [Red:User Warning OFF]"

#define VIRUS_COMMENT   	"Probably infected with Worm Virus"
#define EMAIL_COMMENT   	"Probably infected with E-Mail Virus" 
#define HTTP_COMMENT    	"Burst WEB connection or check Virus"
#define SORIBADA_COMMENT	"Soribada detected"
#define EDONKEY_COMMENT	 	"e-Donkey detected"
#define VSHARE_COMMENT  	"V-Share detected"
#define WINMX_COMMENT    	"WinMX detected"
#define FILEGURI_COMMENT    	"FileGuri detected"
#define KAZAA_COMMENT     	"KaZaA detected"
#define BATTLENET_COMMENT     	"Battle Net detected"
#define OTHERS_COMMENT    	"Unknown Port detected. Watch out"
#endif

#define LIB_NETCONF_WIRELESS_KOREA                  "France"
#define LIB_NETCONF_WIRELESS_CHINA                  "Chine"
#define LIB_NETCONF_WIRELESS_USA                    "Etats-Unis,Canada,Taiwan"
#define LIB_NETCONF_WIRELESS_JAPAN                  "Japon"
#define LIB_NETCONF_WIRELESS_OTHERS                 "Europe"
#define LIB_NETCONF_WIRELESS_EU    	                "Europe"


#define LIB_DDNS_SUCCESS                  "Mise à jour réussie !"
#define LIB_DDNS_BAD_AUTH                 "Mauvaise authentification (nom d'utilisateur ou mot de passe) "
#define LIB_DDNS_PARAMETER_INVALID        "Paramètre incorrect !"
#define LIB_DDNS_BLOCKED                  "Le client a été bloqué."
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "Nom de domaine inconnu !"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "Le nom d'hôte n'existe pas."
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "User is not a donator"
#define LIB_DDNS_NOT_YOURS                "Le nom d'hôte n'est pas le vôtre."
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "Le nom de domaine personnalisé n'est pas activé."
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "Le nom d'hôte est bloqué pour abus"
#define LIB_DDNS_TOO_MANY_OR_FEW          "Pas assez ou trop d'hôtes trouvés"
#define LIB_DDNS_DDNS_ERROR               "Erreur de DNS rencontrée !"
#define LIB_DDNS_SERVER_SHUTDOWN          "Serveur arrêté"
#define LIB_DDNS_CONN_FAIL                "Echec de la connexion !"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "Un autre hôte a déjà été enregistré."
#define LIB_DDNS_UNKNOWN_ERROR            "Erreur inconnue !"

