#define LATEST_TIME     	"最近檢測時間"
#define IPADDRESS       	"IP位址"
#define PROTOCOL        	"通訊協定"
#define FREQUENCY       	"頻率"
#define COMMENT         	"說明 [紅色：用戶警告關閉]"

#define VIRUS_COMMENT   	"可能感染了WORM病毒"
#define EMAIL_COMMENT   	"可能感染了E-Mail病毒"
#define HTTP_COMMENT    	"加速連線或檢查病毒"
#define SORIBADA_COMMENT	"已偵測到Soribada"
#define EDONKEY_COMMENT	 	"已偵測到e-Donkey"
#define VSHARE_COMMENT  	"已偵測到V-Share"
#define WINMX_COMMENT    	"已偵測到WinMX"
#define FILEGURI_COMMENT    	"已偵測到FileGuri"
#define KAZAA_COMMENT     	"已偵測到KaZaA"
#define BATTLENET_COMMENT     	"已偵測到Battle.Net"
#define OTHERS_COMMENT    	"已偵測到未知通訊埠.請注意"

#define LIB_NETCONF_WIRELESS_KOREA                  "韓國"
#define LIB_NETCONF_WIRELESS_EU                     "歐洲"
#define LIB_NETCONF_WIRELESS_CHINA                  "中國"
#define LIB_NETCONF_WIRELESS_USA                    "美國,加拿大,台灣"
#define LIB_NETCONF_WIRELESS_JAPAN                  "日本"
#define LIB_NETCONF_WIRELESS_OTHERS                 "其他"
